name: labs-calling-deploymnet-workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: vikramk20/deployment-workflow/.github/workflows/main.yml@main
    with:
      username: vikramk20
    secrets:
      token: ${{ secrets.TOKEN }}
