name: labs-calling-deploymnet-workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    -name: Test
    run: |
          echo $ORG_A
    env:
          ORG_A: ${{ secrets.ORG_TEST }}
   
